### PR TITLE
Add Apache Commons Imaging

### PR DESCRIPTION
**Pull request by kinow**
Need to complete the packages/modules relationships, and might have to also understand better how to tweak the `experiment.xml` file.

https://github.com/openjournals/joss-reviews/issues/2791

### CODE REVIEW

**Comment by tobias-dv-lnu** [comment]
Nice!
The experiments.xml file is not that important. The important part is the sysmdl as this defines the ground truth mapping that the experiments use.

Looking at the file I think you got the gist of it. One thought is if there is a more general module "format"? Or if the individual formats should be treated as separate modules? I guess it depends on the level of abstraction but maybe also on if the individual formats have some differences regarding intended/allowed dependencies.

It would also be interesting to know if there are alternative module views, that does not follow the package structure.

In the experiments, you can then use different styles of mappers/attraction functions (with different parameter settings), and initial set sizes and prioritize different metrics in the generation of the initial set. Basically, we are evaluating different attraction functions and try to find the optimal parameters for them, generally speaking, it is a parameter optimization problem.

Please let me know if/how I can help 👍

**Comment by kinow** [comment]
>The experiments.xml file is not that important. The important part is the sysmdl as this defines the ground truth mapping that the experiments use.

Excellent, that should make it easier then.

>Looking at the file I think you got the gist of it. One thought is if there is a more general module "format"? Or if the individual formats should be treated as separate modules? I guess it depends on the level of abstraction but maybe also on if the individual formats have some differences regarding intended/allowed dependencies.

That's a very good point. I'm trying to create a more high-level view of the modules. The only modules that I think are more elaborate and would have a meaningful structure, are JPEG and TIFF.

But I think it would be better to start with the formats separated this way.

Each format takes care of its own parsing, writing, reading, etc. There is some code in the "base" and "common" packages that is shared by the formats (I think this is the closest the to "format" module you mentioned above).

>It would also be interesting to know if there are alternative module views, that does not follow the package structure.

Hmmm, interesting. I'm not sure. The formats are well organized. Most Apache Commons components are very small, and their functionalities are kept within a certain scope, and used externally (i.e. there are modules that may not have any relationship with other modules in the source code, but are used/consumed by external users).

However, as the JPEG and TIFF modules are expanding, perhaps if we looked at their structures, we might notice some elements that could be grouped together. The final forms of these groups probably wouldn't match with the modules, I think.

I guess there might exist some existing techniques for clustering of modules (via Java packages, relationships, rules, etc?). Would be interesting if `s4rdm3x` supported this option too, to scan the code and try to automatically create these relationships (I don't think that's possible right now?)

>In the experiments, you can then use different styles of mappers/attraction functions (with different parameter settings), and initial set sizes and prioritize different metrics in the generation of the initial set. Basically, we are evaluating different attraction functions and try to find the optimal parameters for them, generally speaking, it is a parameter optimization problem.

Here's where it's still a bit fuzzy for me, without reading more of the references and theory behind.

What's being optimized here? I thought `s4rdm3x` would try to scan my code, and display which modules are breaking my rules, and also show how dependent one module is to another? Is the tool able to suggest changes in the code? So far I could only see information that reminds me of Stan4J, NDepend; but also some information that I could understand how I would use to help improve my code.

Thanks @tobias-dv-lnu !
Bruno

**Comment by kinow** [comment]
I think the packages/modules are correct now. Generated they from the package structure: https://nbviewer.jupyter.org/github/kinow/notebooks/blob/master/python/java/s4rdm3x.ipynb

**Comment by tobias-dv-lnu** [comment]
> 
> > Looking at the file I think you got the gist of it. One thought is if there is a more general module "format"? Or if the individual formats should be treated as separate modules? I guess it depends on the level of abstraction but maybe also on if the individual formats have some differences regarding intended/allowed dependencies.
> 
> That's a very good point. I'm trying to create a more high-level view of the modules. The only modules that I think are more elaborate and would have a meaningful structure, are JPEG and TIFF.
> 
> But I think it would be better to start with the formats separated this way.
> 
> Each format takes care of its own parsing, writing, reading, etc. There is some code in the "base" and "common" packages that is shared by the formats (I think this is the closest the to "format" module you mentioned above).
>
Yes, I agree that it's often better to start more concrete and then move into abstraction.

One thing that could be of interest is that you can also define modules that are not part of the implementation. In some cases, the purpose of a module is to act as a layer or facade for some external API and this can be an important part of the modular architecture. For example, in an MVC architecture where the view uses AWT, you probably do not want classes in the model module to depend on AWT.

> > It would also be interesting to know if there are alternative module views, that does not follow the package structure.
> 
> Hmmm, interesting. I'm not sure. The formats are well organized. Most Apache Commons components are very small, and their functionalities are kept within a certain scope, and used externally (i.e. there are modules that may not have any relationship with other modules in the source code, but are used/consumed by external users).
> 
> However, as the JPEG and TIFF modules are expanding, perhaps if we looked at their structures, we might notice some elements that could be grouped together. The final forms of these groups probably wouldn't match with the modules, I think.

Having well defined alternative modular views is not that common in my experience. I would guess that the modular structure is well represented by packages at some level of abstraction if the scope of the component is small and well defined.

> I guess there might exist some existing techniques for clustering of modules (via Java packages, relationships, rules, etc?). Would be interesting if `s4rdm3x` supported this option too, to scan the code and try to automatically create these relationships (I don't think that's possible right now?)
Yes, automatic clustering is highly related to what we are doing, the difference is basically that the architect is free to define the architectural modules independent of the actual packages. This can be important in some cases, for example, if you want to do a major refactoring on an architectural level.

There is actually a gui for defining the architecture of a system currently in the implementation, but it has been disabled for the moment to focus more on the experiment generation part. The idea is that it should also support mapping the code etc (essentially a gui to create the sysmdl files).

> > In the experiments, you can then use different styles of mappers/attraction functions (with different parameter settings), and initial set sizes and prioritize different metrics in the generation of the initial set. Basically, we are evaluating different attraction functions and try to find the optimal parameters for them, generally speaking, it is a parameter optimization problem.
> 
> Here's where it's still a bit fuzzy for me, without reading more of the references and theory behind.
> 
> What's being optimized here? I thought `s4rdm3x` would try to scan my code, and display which modules are breaking my rules, and also show how dependent one module is to another? Is the tool able to suggest changes in the code? So far I could only see information that reminds me of Stan4J, NDepend; but also some information that I could understand how I would use to help improve my code.

The main goal of s4rdm3x is to evaluate different code to module mappers, this is a step that is needed so that you can later check if the source code conforms to the modules (regarding allowed dependencies). However, some studies suggest that just comparing the manual mapping to an automatic mapping also suggests classes with issues. E.g. you define a class to be part of a certain module, however, an automatic mapper looks at the implementation it thinks belongs to some other module, there is a fair chance that the implementation is strange in some way. This is what you would see in the Failed Mappings window and it could be a starting point for checking classes that often get misplaced.
In either case, we want an automatic mapper that is as good as possible and that is the basic purpose of s4rdm3x, evaluation of different mapping techniques, and testing/optimizing their parameters.

**Pull request merged**
